### ISSUE TITLE
jsondl is not rendered in Helmet

### ISSUE THREAD

**Issue by Saeeed-B** [Meteor-Community-Packages/react-router-ssr#13] opened 2021-08-24 12:44 UTC
**jsondl is not rendered in Helmet.**

When I look at `inspect `we see jsondl code.
But when I look at the `view page source`, all the tags are rendered except the jsondl tag

I used exactly the following code in my component : 

```
  <Helmet>
                        <title>{this.props.article.title}</title>
                        <meta charSet="utf-8" />
                        <meta name="apple-mobile-web-app-capable" content="yes" />
                        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                        <meta name="description" content={this.props.article.title}  />
                        <meta name="article:section" content="مقالات" />
                        <meta name="article:author" content={this.props.user.profile.Name + ' ' + this.props.user.profile.LastName} />


                        {/* OG */}
                        <meta property="og:title" content={this.props.article.title}  />
                        <meta property="og:description" content="بروز ترین مقالات و آثار در عرصه انقلاب اسلامی و جهان اسلام" />
                        <meta property="og:site_name" content="وبسایت قدر" />
                        <meta property="og:brand" content="وبسایت قدر" />
                        <meta property="og:locale" content="fa" />
                        <meta property="og:url" content={`https://ghadr.org/article/${this.props.slug}`} />
                        <meta property="og:image" content={this.props.article.img} />
                        <meta property="og:type" content="article" />

                        {/* twitter */}
                        <meta name="twitter:title" content={this.props.article.title} />
                        <meta name="twitter:description" content={this.props.article.title} />
                        <meta name="twitter:site" content="@ghadr_org" />
                        <meta name="twitter:card" content="summary" />
                        
                        {/* application/ld+json */}
                        <script type="application/ld+json">
                            {`
                                { 
                                    "@context": "https://schema.org", 
                                    "@type": "Article",
                                    "headline": "${this.props.article.title}",
                                    "alternativeHeadline": "${this.props.article.title}",
                                    "image": "${this.props.article.img}",
                                    "author": "${this.props.user.profile.Name + ' ' + this.props.user.profile.LastName}", 
                                    "editor": "${this.props.user.profile.Name + ' ' + this.props.user.profile.LastName}", 
                                    "keywords": "${this.props.article.title}", 
                                    "publisher": {
                                        "@context":"https://schema.org",
                                        "@type": "Organization",
                                        "name": "ghadr.org",
                                        "alternateName": "وبسایت قدر",
                                        "url": "https://ghadr.org",
                                        "logo": "https://ghadr.org/GhadrLogo.png",
                                        "email":"ghadr.org@gmail.com",
                                        "telephone":"+989162734878",
                                        "brand":"ghadr",
                                        "founder":{
                                                "additionalName":"saeed",
                                                "familyName":"bahrami",
                                                "email":"qmksbp@hotmail.com",
                                                "birthDate":"2000",
                                                "birthPlace":"iran",
                                                "brand":"ghadr",
                                                "contactPoint":
                                                {
                                                    "hoursAvailable":{
                                                        "opens": "06:00:00",
                                                        "closes": "24:00:00"
                                                    },
                                                "email":"qmksbp@hotmail.com",
                                                    "areaServed":"iran",
                                                    "telephone":"+989162734878",
                                                    "availableLanguage":["persian","arabic","english"]
                                                }
                                        },
                                        "contactPoint":{
                                                "hoursAvailable":{
                                                        "opens": "06:00:00",
                                                        "closes": "24:00:00"
                                                },
                                            "email":"qmksbp@hotmail.com",
                                                "contactType":"support",
                                                "areaServed":"iran",
                                                "telephone":"+989162734878",
                                                "availableLanguage":"persian"
                                            },
                                        "sameAs": [
                                            "https://www.instagram.com/ghadr_org/",
                                            "https://ghadr.org",
                                            "https://www.twitter.com/ghadr_org"
                                        ]
                                    },
                                    "url": "https://ghadr.org/article/${this.props.slug}",
                                        "mainEntityOfPage": {
                                        "@type": "WebPage",
                                        "@id": "https://ghadr.org/article"
                                    },
                                    "datePublished": "${this.props.article.createdAt}",
                                    "dateCreated": "${this.props.article.createdAt}",
                                    "dateModified": "${this.props.article.updatedAt}",
                                    "description": "${`${this.props.article.short}`}",
                                    "articleBody": "${`${this.props.article.short}`}"   
                                }
                            `}
                        </script>
                    </Helmet>

```

**Comment by Saeeed-B** [comment] 2021-08-24 12:45
@copleykj This means that Google cannot see the jsondl tag

**Comment by Saeeed-B** [comment] 2021-08-24 12:55
@copleykj 
In fact, the `jsondl `tag will not load until `Ui `is loaded

**Comment by copleykj** [comment] 2021-08-24 12:57
@Saeeed-B I'm gonna need more details on how this works before I can give suggestions on a fix.

As far as I can tell from the information you have given, you are using helmet to add a script tag to the head of the document and expecting that script to somehow execute on the server which is just not possible.

**Comment by Saeeed-B** [comment] 2021-08-24 13:05
@copleykj 
Yes, exactly, I want the `jsondl tag ` to be rendered on the server as well

**Comment by Saeeed-B** [comment] 2021-08-24 13:08
@copleykj 
But seeing the page view source, I realized that this tag is not rendered by the server.
If you want to see an example, check out the page below. Please compare `head ` in `inspect ` and `view page source`

**Comment by copleykj** [comment] 2021-08-24 13:11
Oh.. I understand better. It's not executing, it's just stringified Jason data. I'll look into this.

**Comment by Saeeed-B** [comment] 2021-08-24 13:12
@copleykj 
Sorry I forgot to write the example link: :
[https://ghadr.org/article/elites-in-developed-and-developing-countries](https://ghadr.org/article/elites-in-developed-and-developing-countries)

**Comment by Saeeed-B** [comment] 2021-08-24 13:15
@copleykj 
I guess this problem does not exist in [ react helmet async.](https://www.npmjs.com/package/react-helmet-async)
But your package does not support it.
I do not know exactly maybe

**Comment by copleykj** [comment] 2021-08-24 14:08
No, this is actually caused by the package not rendering some tags to the head. If possible I'll try to get a fix out in the next few hours.

**Comment by copleykj** [comment] 2021-08-25 14:17
v3.0.4 should fix this issue. Closing this for now. Let me know if you have any other issues.

**Closed by copleykj** 2021-08-25 14:17 UTC
